import type {
  CapabilityItem,
  CapabilityProminence,
  PortfolioData,
} from './portfolio.types.ts'
import { validatePortfolio } from './validatePortfolio.ts'

function capabilityItems(
  items: Array<
    [
      id: string,
      label: string,
      prominence: CapabilityProminence,
      featured: boolean,
      evidence: string,
    ]
  >,
): CapabilityItem[] {
  return items.map(([id, label, prominence, featured, evidence]) => ({
    id,
    label,
    prominence,
    featured,
    evidence,
    status: 'published',
    verificationStatus: 'confirmed',
  }))
}

const portfolioData = {
  identity: {
    name: 'Franci Hoxha',
    title: 'Full-Stack Software Developer',
    heroStatement: 'Building modern software experiences, from idea to production.',
    capabilityLine: 'Web • Mobile • Backend • AI',
    summary:
      'I work across frontend, backend, data, mobile applications, and AI integration to move software from idea toward production.',
  },
  metadata: {
    title: 'Franci Hoxha - Full-Stack Software Developer',
    description:
      'Portfolio of Franci Hoxha, a Full-Stack Software Developer building modern web, mobile, backend, and AI-integrated software from idea to production.',
    siteName: 'Franci Hoxha',
    // Prepared, not published. The social card exists as a static asset and is
    // regenerated by `npm run generate:social`, but no og:image/twitter:image
    // field is emitted until an approved canonical domain allows an absolute
    // URL. See the Phase 9 implementation record.
    socialImagePath: '/og-image.png',
    socialImageAlt:
      'Franci Hoxha, Full-Stack Software Developer. Web, Mobile, Backend, AI.',
    socialImageWidth: 1200,
    socialImageHeight: 630,
    // No approved canonical portfolio domain exists yet (plan Section 30.1,
    // question 6), so this is null and every URL-dependent field stays
    // omitted rather than publishing a deployment host as the canonical
    // address. Populating it is the intended path once the domain is
    // approved; nothing here forbids that.
    canonicalUrl: null,
  },
  navigation: [
    { id: 'work', label: 'Work', href: '#work', status: 'published' },
    { id: 'stack', label: 'Stack', href: '#stack', status: 'published' },
    { id: 'journey', label: 'Journey', href: '#journey', status: 'published' },
    {
      id: 'credentials',
      label: 'Credentials',
      href: '#credentials',
      status: 'published',
    },
    { id: 'ai', label: 'Ask AI', href: '#ai', status: 'published' },
    { id: 'contact', label: 'Contact', href: '#contact', status: 'published' },
  ],
  contact: [
    {
      id: 'email',
      label: 'Email',
      value: 'francihoxha@yahoo.com',
      href: 'mailto:francihoxha@yahoo.com',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
    // Phone stays unpublished. Public phone visibility is an explicitly
    // unresolved gate (plan Section 30.1, question 2) and the stored number is
    // only repository-current, not confirmed as Franci's public portfolio
    // number. The record is retained so a later confirmation is a one-flag
    // change rather than a rediscovery.
    {
      id: 'phone',
      label: 'Phone',
      value: '+355 69 253 8842',
      href: 'tel:+355692538842',
      public: false,
      assistantVisible: false,
      status: 'draft',
      verificationStatus: 'needs-confirmation',
    },
    {
      id: 'location',
      label: 'Location',
      value: 'Tirana, Albania',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
    {
      id: 'linkedin',
      label: 'LinkedIn',
      value: 'View profile',
      href: 'https://www.linkedin.com/in/franci-hoxha-78a174329/',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
  ],
  projects: [
    {
      id: 'planify',
      title: 'Planify.al',
      category: 'Software Project',
      label: 'Flagship Software Project',
      description: 'Planify is my flagship software project.',
      featured: true,
      previewAssetId: 'planify-preview',
      previewPosition: '48% 8%',
      link: {
        label: 'View Planify',
        href: 'https://planify.al',
        external: true,
        status: 'published',
        verificationStatus: 'repository-current',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'barberspot',
      title: 'BarberSpot.al',
      category: 'Software Project',
      description: 'BarberSpot.al is part of my selected software work.',
      featured: false,
      link: {
        label: 'View BarberSpot',
        href: 'https://barberspot.al',
        external: true,
        status: 'published',
        verificationStatus: 'repository-current',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'charging-station',
      title: 'Online Charging Station Management System',
      category: 'Software Project',
      description: 'One of my selected software projects focuses on charging-station management.',
      featured: false,
      link: {
        label: 'Discuss the project',
        href: '#contact',
        external: false,
        status: 'published',
        verificationStatus: 'confirmed',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  capabilityGroups: [
    {
      id: 'frontend',
      title: 'Frontend',
      status: 'published',
      items: capabilityItems([
        [
          'react',
          'React',
          'primary',
          true,
          'I use React to build component-based application interfaces.',
        ],
        [
          'nextjs',
          'Next.js',
          'primary',
          true,
          'Used for full-stack web application work that connects interface and server-backed flows.',
        ],
        [
          'html',
          'HTML',
          'supporting',
          false,
          'Used as the semantic structure beneath accessible web interfaces.',
        ],
        [
          'css',
          'CSS',
          'supporting',
          false,
          'Used to build responsive layouts, interaction states, and visual presentation.',
        ],
        [
          'responsive',
          'Responsive interfaces',
          'primary',
          false,
          'Applied to interfaces that adapt across desktop and mobile viewports.',
        ],
        [
          'frontend-backend',
          'Frontend/backend integration',
          'primary',
          false,
          'Used to connect visible application flows with APIs and application logic.',
        ],
        [
          'pwa',
          'PWA-related application work',
          'supporting',
          false,
          'I have worked with PWA-related application patterns as part of responsive web experiences.',
        ],
      ]),
    },
    {
      id: 'backend',
      title: 'Backend / APIs',
      status: 'published',
      items: capabilityItems([
        [
          'node-api',
          'Node.js / API development',
          'primary',
          true,
          'Used for JavaScript and TypeScript API development and application-side services.',
        ],
        [
          'rest',
          'REST APIs',
          'primary',
          false,
          'Used to connect frontend and mobile-facing application flows with backend services.',
        ],
        [
          'fastapi',
          'FastAPI',
          'supporting',
          false,
          'Used with Python for API-oriented backend work.',
        ],
        [
          'authentication',
          'Authentication',
          'primary',
          false,
          'Applied to sign-in and identity control in application systems.',
        ],
        [
          'authorization',
          'Authorization',
          'primary',
          false,
          'Applied to access control and permission-aware application behavior.',
        ],
        [
          'business-logic',
          'Application/business logic',
          'primary',
          false,
          'Used to implement application behavior between interfaces, APIs, and data.',
        ],
      ]),
    },
    {
      id: 'data',
      title: 'Data',
      status: 'published',
      items: capabilityItems([
        [
          'mongodb',
          'MongoDB',
          'primary',
          true,
          'Used as a primary data capability in database-backed application work.',
        ],
        [
          'database-apps',
          'Database-backed applications',
          'primary',
          false,
          'Used to persist and retrieve application state behind backend flows.',
        ],
        [
          'mysql',
          'MySQL',
          'supporting',
          false,
          'I use MySQL as part of my relational-database toolkit.',
        ],
        [
          'sql-server',
          'SQL Server',
          'supporting',
          false,
          'I have worked with SQL Server as part of my relational-database toolkit.',
        ],
      ]),
    },
    {
      id: 'mobile',
      title: 'Mobile',
      status: 'published',
      items: [
        {
          id: 'mobile-development',
          label: 'Mobile application development',
          prominence: 'primary',
          featured: false,
          evidence:
            'I apply my interface, API, and data experience to mobile application development.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
      ],
    },
    {
      id: 'ai',
      title: 'AI',
      status: 'published',
      items: [
        {
          id: 'ai-integration',
          label: 'AI integration',
          prominence: 'primary',
          featured: false,
          evidence:
            'I integrate AI into software workflows, including this portfolio assistant.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
        {
          id: 'ai-assisted-development',
          label: 'AI-assisted development',
          prominence: 'supporting',
          featured: false,
          evidence:
            'I use AI in my development workflow to support implementation and problem-solving.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
      ],
    },
    {
      id: 'engineering',
      title: 'Engineering / Delivery',
      status: 'published',
      items: capabilityItems([
        [
          'git',
          'Git',
          'primary',
          false,
          'Used to manage and review source changes across application work.',
        ],
        [
          'testing',
          'Testing',
          'primary',
          false,
          'Used to verify application behavior and reduce regression risk.',
        ],
        [
          'debugging',
          'Debugging',
          'primary',
          false,
          'Used to trace failures across interface, service, and data boundaries.',
        ],
        [
          'deployment',
          'Deployment',
          'primary',
          false,
          'Used to move application work from local development toward a live environment.',
        ],
        [
          'hardening',
          'Production hardening',
          'supporting',
          false,
          'Applied as a supporting discipline when preparing application behavior for production.',
        ],
        [
          'integration',
          'Application integration',
          'primary',
          false,
          'Used to connect independently implemented parts into one application system.',
        ],
        [
          'troubleshooting',
          'Troubleshooting',
          'primary',
          false,
          'I draw on software work and hands-on IT support across operating systems when troubleshooting.',
        ],
      ]),
    },
    {
      id: 'languages',
      title: 'Languages',
      status: 'published',
      items: capabilityItems([
        [
          'javascript',
          'JavaScript',
          'primary',
          true,
          'A primary implementation language across frontend and Node.js-style API work.',
        ],
        [
          'typescript',
          'TypeScript',
          'primary',
          true,
          'A primary language for typed application and integration work.',
        ],
        [
          'python',
          'Python',
          'primary',
          true,
          'I use Python for backend and API work, including FastAPI.',
        ],
        [
          'java',
          'Java',
          'primary',
          true,
          'I use Java as one of the programming languages in my development toolkit.',
        ],
      ]),
    },
  ],
  journeyNarrative: {
    title: 'How my foundations became product thinking',
    introduction:
      'My background started with business and hands-on systems work before moving deeper into software engineering. That combination shapes how I build today: as products used by people and organizations, not code in isolation.',
  },
  journey: [
    {
      id: 'business-education',
      kind: 'education',
      stage: 'business',
      stageLabel: 'Business foundation',
      title: 'Master’s degree in Business Administration',
      description:
        'Completing my Master’s degree in Business Administration gave me a strong understanding of organizations, operations, customers, and the processes that connect them.',
      bridge:
        'That business foundation gave me a practical starting point for understanding how systems support people and organizations.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'it-support',
      kind: 'experience',
      stage: 'systems',
      stageLabel: 'IT / systems foundation',
      title: 'Computer Technician & IT Support',
      description:
        'I supported users and systems across Windows, macOS, and Linux, developing hands-on experience in hardware and software troubleshooting, maintenance, backup and recovery, and end-user support.',
      bridge:
        'Working close to real systems made reliability, clear diagnosis, and user needs part of how I approach technical problems.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'masters',
      kind: 'education',
      stage: 'engineering',
      stageLabel: 'Software engineering',
      period: 'Completed July 2026',
      title: 'Master of Science in Informatics Engineering',
      description:
        'I moved deeper into software engineering through formal study and completed my Master of Science in Informatics Engineering in July 2026.',
      bridge:
        'Software engineering gave me the methods to turn business context and systems thinking into working applications.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'product-development',
      kind: 'practice',
      stage: 'product',
      stageLabel: 'Product development',
      title: 'Building software as a product',
      description:
        'Today, I apply those foundations to product development across interfaces, APIs, data, testing, and delivery—including the software work presented in this portfolio.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  credentialsNarrative: {
    title: 'Selected learning that supports the path',
    introduction:
      'These three 2026 credentials extend my software-engineering foundation and the way I apply AI in development. They support the work; they do not replace it.',
    handoff:
      'The portfolio assistant below is one practical example of how I apply AI integration in a software experience.',
  },
  credentials: [
    {
      id: 'software-engineering-build-better-software',
      title: 'Complete Software Engineering Course: Build Better Software',
      provider: 'Udemy',
      instructors: ['Yogesh Dahake'],
      completedOn: '2026-06-23',
      durationHours: 15,
      asset: {
        id: 'credential-software-engineering',
        status: 'available',
        src: '/certificates/software-engineering-build-better-software.jpg',
        alt: 'Udemy certificate for Complete Software Engineering Course: Build Better Software',
        width: 1600,
        height: 1190,
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'ai-coder-claude-code-coding-agents',
      title: 'AI Coder: Complete Claude Code & Coding Agents Course',
      provider: 'Udemy',
      instructors: ['Ligency', 'Ed Donner'],
      completedOn: '2026-06-21',
      durationHours: 16.5,
      asset: {
        id: 'credential-ai-coder',
        status: 'available',
        src: '/certificates/ai-coder-claude-code-coding-agents.jpg',
        alt: 'Udemy certificate for AI Coder: Complete Claude Code & Coding Agents Course',
        width: 1600,
        height: 1190,
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'succeed-in-age-of-ai',
      title: 'Succeed in the Age of AI',
      provider: 'Udemy',
      instructors: ['Dr. Angela Yu'],
      completedOn: '2026-05-18',
      durationHours: 8.5,
      asset: {
        id: 'credential-age-of-ai',
        status: 'available',
        src: '/certificates/succeed-in-age-of-ai.jpg',
        alt: 'Udemy certificate for Succeed in the Age of AI',
        width: 1600,
        height: 1190,
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  contactNarrative: {
    eyebrow: 'Contact',
    title: 'Let’s build something useful.',
    introduction:
      'That is the point of everything above. If you are hiring, planning a product, or reviewing this portfolio for a role, email is the most direct route. The CV and my LinkedIn profile cover the same ground in more detail.',
    emailCtaLabel: 'Email me',
    cvCtaLabel: 'Download CV',
  },
  languages: [],
  availability: null,
  assets: [
    {
      id: 'cv',
      status: 'available',
      src: '/Franci-Hoxha-CV.pdf',
    },
    {
      id: 'planify-preview',
      status: 'available',
      src: '/planify-preview.png',
      alt: 'Planify dashboard preview',
      width: 1200,
      height: 628,
    },
  ],
  assistant: {
    suggestedQuestions: [
      'What projects has Franci built?',
      'What technologies does he work with?',
      'Tell me about Planify.',
      'What is his professional background?',
      'What AI experience does he have?',
    ],
  },
} satisfies PortfolioData

export const portfolio = validatePortfolio(portfolioData)
