import type {
  CapabilityItem,
  CapabilityProminence,
  PortfolioData,
} from './portfolio.types.ts'
import { validatePortfolio } from './validatePortfolio.ts'

function capabilityItems(
  items: Array<
    [
      id: string,
      label: string,
      prominence: CapabilityProminence,
      featured: boolean,
      evidence: string,
    ]
  >,
): CapabilityItem[] {
  return items.map(([id, label, prominence, featured, evidence]) => ({
    id,
    label,
    prominence,
    featured,
    evidence,
    status: 'published',
    verificationStatus: 'confirmed',
  }))
}

const portfolioData = {
  identity: {
    name: 'Franci Hoxha',
    title: 'Full-Stack Software Developer',
    heroStatement: 'Building modern software experiences, from idea to production.',
    capabilityLine: 'Web • Mobile • Backend • AI',
    summary:
      'I work across frontend, backend, data, mobile applications, and AI integration to move software from idea toward production.',
  },
  metadata: {
    title: 'Franci Hoxha - Full-Stack Software Developer',
    description:
      'Franci Hoxha is a Full-Stack Software Developer building modern web, mobile, backend, and AI-integrated software experiences.',
  },
  navigation: [
    { id: 'work', label: 'Work', href: '#work', status: 'published' },
    { id: 'stack', label: 'Stack', href: '#stack', status: 'published' },
    { id: 'journey', label: 'Journey', href: '#journey', status: 'published' },
    {
      id: 'credentials',
      label: 'Credentials',
      href: '#credentials',
      status: 'published',
    },
    { id: 'ai', label: 'Ask AI', href: '#ai', status: 'published' },
    { id: 'contact', label: 'Contact', href: '#contact', status: 'published' },
  ],
  contact: [
    {
      id: 'email',
      label: 'Email',
      value: 'francihoxha@yahoo.com',
      href: 'mailto:francihoxha@yahoo.com',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
    {
      id: 'phone',
      label: 'Phone',
      value: '+355 69 253 8842',
      href: 'tel:+355692538842',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
    {
      id: 'location',
      label: 'Location',
      value: 'Tirana, Albania',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
    {
      id: 'linkedin',
      label: 'LinkedIn',
      value: 'View profile',
      href: 'https://www.linkedin.com/in/franci-hoxha-78a174329/',
      public: true,
      assistantVisible: false,
      status: 'published',
      verificationStatus: 'repository-current',
    },
  ],
  projects: [
    {
      id: 'planify',
      title: 'Planify.al',
      category: 'Software Project',
      label: 'Flagship Software Project',
      description: 'Planify is my flagship software project.',
      featured: true,
      previewAssetId: 'planify-preview',
      previewPosition: '48% 8%',
      link: {
        label: 'View Planify',
        href: 'https://planify.al',
        external: true,
        status: 'published',
        verificationStatus: 'repository-current',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'barberspot',
      title: 'BarberSpot.al',
      category: 'Software Project',
      description: 'BarberSpot.al is part of my selected software work.',
      featured: false,
      link: {
        label: 'View BarberSpot',
        href: 'https://barberspot.al',
        external: true,
        status: 'published',
        verificationStatus: 'repository-current',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'charging-station',
      title: 'Online Charging Station Management System',
      category: 'Software Project',
      description: 'One of my selected software projects focuses on charging-station management.',
      featured: false,
      link: {
        label: 'Discuss the project',
        href: '#contact',
        external: false,
        status: 'published',
        verificationStatus: 'confirmed',
      },
      stack: [],
      highlights: [],
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  capabilityGroups: [
    {
      id: 'frontend',
      title: 'Frontend',
      status: 'published',
      items: capabilityItems([
        [
          'react',
          'React',
          'primary',
          true,
          'I use React to build component-based application interfaces.',
        ],
        [
          'nextjs',
          'Next.js',
          'primary',
          true,
          'Used for full-stack web application work that connects interface and server-backed flows.',
        ],
        [
          'html',
          'HTML',
          'supporting',
          false,
          'Used as the semantic structure beneath accessible web interfaces.',
        ],
        [
          'css',
          'CSS',
          'supporting',
          false,
          'Used to build responsive layouts, interaction states, and visual presentation.',
        ],
        [
          'responsive',
          'Responsive interfaces',
          'primary',
          false,
          'Applied to interfaces that adapt across desktop and mobile viewports.',
        ],
        [
          'frontend-backend',
          'Frontend/backend integration',
          'primary',
          false,
          'Used to connect visible application flows with APIs and application logic.',
        ],
        [
          'pwa',
          'PWA-related application work',
          'supporting',
          false,
          'I have worked with PWA-related application patterns as part of responsive web experiences.',
        ],
      ]),
    },
    {
      id: 'backend',
      title: 'Backend / APIs',
      status: 'published',
      items: capabilityItems([
        [
          'node-api',
          'Node.js / API development',
          'primary',
          true,
          'Used for JavaScript and TypeScript API development and application-side services.',
        ],
        [
          'rest',
          'REST APIs',
          'primary',
          false,
          'Used to connect frontend and mobile-facing application flows with backend services.',
        ],
        [
          'fastapi',
          'FastAPI',
          'supporting',
          false,
          'Used with Python for API-oriented backend work.',
        ],
        [
          'authentication',
          'Authentication',
          'primary',
          false,
          'Applied to sign-in and identity control in application systems.',
        ],
        [
          'authorization',
          'Authorization',
          'primary',
          false,
          'Applied to access control and permission-aware application behavior.',
        ],
        [
          'business-logic',
          'Application/business logic',
          'primary',
          false,
          'Used to implement application behavior between interfaces, APIs, and data.',
        ],
      ]),
    },
    {
      id: 'data',
      title: 'Data',
      status: 'published',
      items: capabilityItems([
        [
          'mongodb',
          'MongoDB',
          'primary',
          true,
          'Used as a primary data capability in database-backed application work.',
        ],
        [
          'database-apps',
          'Database-backed applications',
          'primary',
          false,
          'Used to persist and retrieve application state behind backend flows.',
        ],
        [
          'mysql',
          'MySQL',
          'supporting',
          false,
          'I use MySQL as part of my relational-database toolkit.',
        ],
        [
          'sql-server',
          'SQL Server',
          'supporting',
          false,
          'I have worked with SQL Server as part of my relational-database toolkit.',
        ],
      ]),
    },
    {
      id: 'mobile',
      title: 'Mobile',
      status: 'published',
      items: [
        {
          id: 'mobile-development',
          label: 'Mobile application development',
          prominence: 'primary',
          featured: false,
          evidence:
            'I apply my interface, API, and data experience to mobile application development.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
      ],
    },
    {
      id: 'ai',
      title: 'AI',
      status: 'published',
      items: [
        {
          id: 'ai-integration',
          label: 'AI integration',
          prominence: 'primary',
          featured: false,
          evidence:
            'I integrate AI into software workflows, including this portfolio assistant.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
        {
          id: 'ai-assisted-development',
          label: 'AI-assisted development',
          prominence: 'supporting',
          featured: false,
          evidence:
            'I use AI in my development workflow to support implementation and problem-solving.',
          status: 'published',
          verificationStatus: 'confirmed',
        },
      ],
    },
    {
      id: 'engineering',
      title: 'Engineering / Delivery',
      status: 'published',
      items: capabilityItems([
        [
          'git',
          'Git',
          'primary',
          false,
          'Used to manage and review source changes across application work.',
        ],
        [
          'testing',
          'Testing',
          'primary',
          false,
          'Used to verify application behavior and reduce regression risk.',
        ],
        [
          'debugging',
          'Debugging',
          'primary',
          false,
          'Used to trace failures across interface, service, and data boundaries.',
        ],
        [
          'deployment',
          'Deployment',
          'primary',
          false,
          'Used to move application work from local development toward a live environment.',
        ],
        [
          'hardening',
          'Production hardening',
          'supporting',
          false,
          'Applied as a supporting discipline when preparing application behavior for production.',
        ],
        [
          'integration',
          'Application integration',
          'primary',
          false,
          'Used to connect independently implemented parts into one application system.',
        ],
        [
          'troubleshooting',
          'Troubleshooting',
          'primary',
          false,
          'I draw on software work and hands-on IT support across operating systems when troubleshooting.',
        ],
      ]),
    },
    {
      id: 'languages',
      title: 'Languages',
      status: 'published',
      items: capabilityItems([
        [
          'javascript',
          'JavaScript',
          'primary',
          true,
          'A primary implementation language across frontend and Node.js-style API work.',
        ],
        [
          'typescript',
          'TypeScript',
          'primary',
          true,
          'A primary language for typed application and integration work.',
        ],
        [
          'python',
          'Python',
          'primary',
          true,
          'I use Python for backend and API work, including FastAPI.',
        ],
        [
          'java',
          'Java',
          'primary',
          true,
          'I use Java as one of the programming languages in my development toolkit.',
        ],
      ]),
    },
  ],
  journey: [
    {
      id: 'business-education',
      kind: 'education',
      title: 'Business Administration studies',
      description: 'My business education forms part of my path into software development.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'it-support',
      kind: 'experience',
      title: 'Computer Technician & IT Support',
      description:
        'I supported users and systems across Windows, macOS, and Linux while developing practical troubleshooting, reliability, documentation, and operational skills.',
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'masters',
      kind: 'education',
      period: 'Completed July 2026',
      title: 'Master’s degree',
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  credentials: [
    {
      id: 'software-engineering-build-better-software',
      title: 'Complete Software Engineering Course: Build Better Software',
      provider: 'Udemy',
      instructors: ['Yogesh Dahake'],
      completedOn: '2026-06-23',
      durationHours: 15,
      asset: {
        id: 'credential-software-engineering',
        status: 'planned',
        plannedPath: 'public/certificates/software-engineering-build-better-software.jpg',
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'ai-coder-claude-code-coding-agents',
      title: 'AI Coder: Complete Claude Code & Coding Agents Course',
      provider: 'Udemy',
      instructors: ['Ligency', 'Ed Donner'],
      completedOn: '2026-06-21',
      durationHours: 16.5,
      asset: {
        id: 'credential-ai-coder',
        status: 'planned',
        plannedPath: 'public/certificates/ai-coder-claude-code-coding-agents.jpg',
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
    {
      id: 'succeed-in-age-of-ai',
      title: 'Succeed in the Age of AI',
      provider: 'Udemy',
      instructors: ['Dr. Angela Yu'],
      completedOn: '2026-05-18',
      durationHours: 8.5,
      asset: {
        id: 'credential-age-of-ai',
        status: 'planned',
        plannedPath: 'public/certificates/succeed-in-age-of-ai.jpg',
      },
      status: 'published',
      verificationStatus: 'confirmed',
    },
  ],
  languages: [],
  availability: null,
  assets: [
    {
      id: 'cv',
      status: 'available',
      src: '/Franci-Hoxha-CV.pdf',
    },
    {
      id: 'planify-preview',
      status: 'available',
      src: '/planify-preview.png',
      alt: 'Planify dashboard preview',
      width: 1200,
      height: 628,
    },
  ],
  assistant: {
    suggestedQuestions: [
      'What has Franci built?',
      'What is his technical stack?',
      'What is his professional background?',
      'What AI experience does he have?',
    ],
  },
} satisfies PortfolioData

export const portfolio = validatePortfolio(portfolioData)
